<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ALIPLR2569" failures="2" tests="2" name="APITest" time="5.485" errors="0" timestamp="30 Oct 2020 09:57:42 GMT">
  <testcase classname="com.api.testCases.VerifyEmailTestCase" name="VerifyEmail" time="2.121">
    <failure type="java.lang.AssertionError" message="expected [202] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [202] but found [401]
at com.api.utilities.ResponseUtilities.VerifyStatusCode(ResponseUtilities.java:38)
at com.api.testCases.VerifyEmailTestCase.VerifyEmail(VerifyEmailTestCase.java:35)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- VerifyEmail -->
  <testcase classname="com.api.testCases.VerifyUserMasterData" name="VerifyUserData" time="3.157">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.api.utilities.ResponseUtilities.verifyJSONElementValue(ResponseUtilities.java:29)
at com.api.testCases.VerifyUserMasterData.VerifyUserData(VerifyUserMasterData.java:36)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- VerifyUserData -->
  <testcase classname="com.api.base.BaseTest" name="@BeforeSuite BeforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BeforeSuite -->
</testsuite> <!-- APITest -->
